# ---------- Dependencies ----------
FROM node:22-alpine AS dependencies

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev && \
    npm cache clean --force


# ---------- Production ----------
FROM node:22-alpine AS production

WORKDIR /app

ENV NODE_ENV=production

ENV PORT=5000

COPY --from=dependencies /app/node_modules ./node_modules

COPY --chown=node:node . .

USER node

EXPOSE 5000

CMD ["node", "server.js"]
